---
- name: AMS
  hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
      
    - name: Install Docker Module for Python
      pip:
        name: docker
        
    - name: Install docker-compose
      apt:
        name: docker-compose
      
    - name: Pull docker image
      docker_image:
        name: "sebp/elk"
        source: pull
        
    - name: Change VM.max_map_count
      command: sudo sysctl -w vm.max_map_count=262144
        
    - name: Copy docker-compose file
      copy:
        src: './templates/docker-compose.yml'
        dest: '/home/'
        mode: 0600
        
    - name: Copy alertmanager config file
      copy:
        src: './templates/alertmanager/'
        dest: '/home/alertmanager/'
        mode: 0600
        
    - name: Copy prometheus config file
      copy:
        src: './templates/prometheus/'
        dest: '/home/prometheus/'
        mode: 0600
        
    - name: build container with docker-compose
      community.docker.docker_compose:
        project_src: "/home/"
      register: options
    
    