---
- name: Install mini-httpd
  apt:
    name: mini-httpd

- name: Copy modules config file
  template:
    src: AMSWebPlatform
    dest: /home
    mode: 0666

- name: Inicialize Web platform
  command: sudo mini_httpd -p 80 -d /home/AMSWebPlatform

