---
- name: Install mini-httpd
  apt:
    name: mini-httpd

- name: Copy Web platform files
  copy:
    src: './roles/webapp/templates/AMSWebPlatform/'
    dest: '/home/AMSWebPlatform/'
    mode: 0666

- name: Inicialize Web platform
  command: sudo mini_httpd -p 80 -d /home/AMSWebPlatform

