---
- name: Copy compose source templates
  template:
    src: docker-compose.yml
    dest: "{{ docker_compose_dir }}"
    mode: 0666

- name: Build container with docker-compose
  become: yes
  docker_compose:
    project_src: "{{ docker_compose_dir }}"
  register: options

- debug: msg={{ options }}

