version: '3'

services:
        elk:
                image: sebp/elk
                ports:
                        - "5601:5601"
                        - "9200:9200"
                        - "5044:5044"
                volumes:
                        - ./configs/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
                        - ./configs/kibana.yml:/opt/kibana/config/kibana.yml
                        - ./configs/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf
                        - ./configs/30-output.conf:/etc/logstash/conf.d/30-output.conf


