global:
  scrape_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/alert.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
            - targets: ['10.8.0.2:9100','10.8.1.2:9100','10.8.2.2:9100']
  - job_name: 'kube-state-metrics'
    static_configs:
            - targets: ['10.8.0.5:8080']


